import {
  BarChart3,
  Bell,
  Bot,
  Bookmark,
  CalendarDays,
  ClipboardList,
  CreditCard,
  FileText,
  Globe,
  Mail,
  Megaphone,
  Package2,
  Puzzle,
  Receipt,
  Settings,
  ShoppingCart,
  Wallet,
  type LucideIcon,
} from "lucide-react"

export type SubItem = { title: string; url: string }
export type NavItem = { title: string; url?: string; icon: LucideIcon; sub?: SubItem[] }

export const NAV: NavItem[] = [
  { title: "Dashboard", url: "/dashboard", icon: BarChart3 },
  {
    title: "Point of Sale",
    icon: CreditCard,
    sub: [
      { title: "Current Sale", url: "/pos" },
      { title: "Drafts", url: "/pos/drafts" },
      { title: "Invoices", url: "/pos/invoices" },
      { title: "Transactions", url: "/pos/transactions" },
      { title: "Returns", url: "/pos/returns" },
      { title: "Start Return", url: "/pos/returns/new" },
    ],
  },
  { title: "Appointments", url: "/appointments", icon: CalendarDays },
  {
    title: "Inventory",
    icon: Package2,
    sub: [
      { title: "Items", url: "/inventory" },
      { title: "New Item", url: "/inventory/new" },
      { title: "Categories", url: "/inventory/categories" },
      { title: "Add Category", url: "/inventory/categories/new" },
      { title: "Units", url: "/inventory/units" },
      { title: "Add Unit", url: "/inventory/units/new" },
      { title: "Brands", url: "/inventory/brands" },
      { title: "Add Brand", url: "/inventory/brands/new" },
      { title: "Warranties", url: "/inventory/warranties" },
      { title: "Add Warranty", url: "/inventory/warranties/new" },
      { title: "Price Lists", url: "/inventory/price-lists" },
      { title: "New Price List", url: "/inventory/price-lists/new" },
      { title: "Composite Items", url: "/inventory/composite" },
      { title: "New Composite", url: "/inventory/composite/new" },
      { title: "Recipes & BOMs", url: "/inventory/recipes" },
      { title: "New Recipe", url: "/inventory/recipes/new" },
      { title: "Production runs", url: "/inventory/production" },
      { title: "Lots & batches", url: "/inventory/lots" },
      { title: "Recall trace", url: "/inventory/recall" },
      { title: "Adjustments", url: "/inventory/adjustments" },
      { title: "Transfers", url: "/inventory/transfers" },
      { title: "Label Print", url: "/inventory/labels" },
      { title: "Receive Stock", url: "/inventory/receive" },
    ],
  },
  {
    title: "Sales",
    icon: ShoppingCart,
    sub: [
      { title: "Customers", url: "/sales/customers" },
      { title: "New Customer", url: "/sales/customers/new" },
      { title: "Orders", url: "/sales/orders" },
      { title: "New Order", url: "/sales/orders/new" },
      { title: "Invoices", url: "/sales/invoices" },
      { title: "New Invoice", url: "/sales/invoices/new" },
      { title: "Shipments", url: "/sales/shipments" },
      { title: "New Shipment", url: "/sales/shipments/new" },
      { title: "Returns", url: "/sales/returns" },
      { title: "New Return", url: "/sales/returns/new" },
      { title: "Discounts", url: "/sales/discounts" },
      { title: "New Discount", url: "/sales/discounts/new" },
      { title: "Sales Leaderboard", url: "/sales/team" },
      { title: "Live Inventory (Sales)", url: "/sales/inventory" },
    ],
  },
  {
    title: "Expenses",
    icon: Receipt,
    sub: [
      { title: "All Expenses", url: "/expenses" },
      { title: "Add Expense", url: "/expenses/new" },
    ],
  },
  {
    title: "Purchases",
    icon: ClipboardList,
    sub: [
      { title: "Vendors", url: "/purchasing/vendors" },
      { title: "Add Vendor", url: "/purchasing/vendors/new" },
      { title: "Purchase Orders", url: "/purchasing/pos" },
      { title: "New Purchase Order", url: "/purchasing/pos/new" },
      { title: "Receipts", url: "/purchasing/receipts" },
      { title: "New Receipt", url: "/purchasing/receipts/new" },
      { title: "Bills", url: "/purchasing/bills" },
      { title: "New Bill", url: "/purchasing/bills/new" },
      { title: "Vendor Credits", url: "/purchasing/vendor-credits" },
      { title: "New Vendor Credit", url: "/purchasing/vendor-credits/new" },
    ],
  },
  {
    title: "Reporting",
    icon: FileText,
    sub: [
      { title: "Profit & Loss", url: "/reporting/profit-loss" },
      { title: "Purchase & Sale", url: "/reporting/purchase-sale" },
      { title: "Tax Analytics", url: "/reporting/tax" },
      { title: "Supplier & Customer", url: "/reporting/supplier-customer" },
      { title: "Customer Group", url: "/reporting/customer-group" },
      { title: "Stock", url: "/reporting/stock" },
      { title: "Stock Expiry", url: "/reporting/stock-expiry" },
      { title: "Stock Adjustment", url: "/reporting/stock-adjustment" },
      { title: "Variance (theoretical vs actual)", url: "/reporting/variance" },
      { title: "Recipe cost watch", url: "/reporting/recipe-cost" },
      { title: "Allergens", url: "/reporting/allergens" },
      { title: "Trending Product", url: "/reporting/trending-product" },
      { title: "Item", url: "/reporting/item" },
      { title: "Product Purchase", url: "/reporting/product-purchase" },
      { title: "Product Sell", url: "/reporting/product-sell" },
      { title: "Purchase Payment", url: "/reporting/purchase-payment" },
      { title: "Sell Payment", url: "/reporting/sell-payment" },
      { title: "Expense", url: "/reporting/expense" },
      { title: "Register", url: "/reporting/register" },
      { title: "Sales Representatives", url: "/reporting/sales-representatives" },
      { title: "Activity Log", url: "/reporting/activity-log" },
    ],
  },
  {
    title: "Accounting",
    icon: Wallet,
    sub: [
      { title: "Profit & Loss",  url: "/accounting/profit-loss" },
      { title: "Balance Sheet",  url: "/accounting/balance-sheet" },
      { title: "Cash Flow",      url: "/accounting/cash-flow" },
      { title: "Payroll",        url: "/accounting/payroll" },
      { title: "Commission Payouts", url: "/accounting/commissions" },
      { title: "Tax Filings",    url: "/accounting/taxes" },
      { title: "Chart of Accounts", url: "/accounting/chart-of-accounts" },
      { title: "Journal Entries",   url: "/accounting/journal-entries" },
      { title: "Bank Reconciliation", url: "/accounting/reconciliation" },
    ],
  },
  {
    title: "Storefront",
    icon: Globe,
    sub: [
      { title: "Manage", url: "/storefront" },
      { title: "Orders", url: "/storefront/orders" },
      { title: "Customers", url: "/storefront/customers" },
      { title: "Products", url: "/storefront/products" },
      { title: "Discounts", url: "/storefront/discounts" },
      { title: "Pages & Content", url: "/storefront/pages" },
      { title: "Analytics", url: "/storefront/analytics" },
      { title: "Domain & DNS", url: "/storefront/domain" },
      { title: "Billing", url: "/storefront/billing" },
      { title: "Settings", url: "/storefront/settings" },
      { title: "Browse Templates", url: "/storefront/templates" },
    ],
  },
  {
    title: "Marketing",
    icon: Megaphone,
    sub: [
      { title: "Overview", url: "/marketing" },
      { title: "Facebook Marketplace", url: "/marketing/facebook-marketplace" },
      { title: "Facebook Ads", url: "/marketing/facebook-ads" },
      { title: "Instagram Ads", url: "/marketing/instagram-ads" },
      { title: "YouTube & AdSense", url: "/marketing/youtube-adsense" },
      { title: "Commissions", url: "/marketing/commissions" },
      { title: "New Listing", url: "/marketing/listings/new" },
    ],
  },
  {
    title: "Communications",
    icon: Mail,
    sub: [
      { title: "Inbox", url: "/communications" },
      { title: "Compose", url: "/communications/new" },
      { title: "Templates", url: "/communications/templates" },
      { title: "Team Chat", url: "/sales/team/chat" },
    ],
  },
  { title: "AI Assistant", url: "/ai", icon: Bot },
  { title: "My Commissions", url: "/affiliate/dashboard", icon: Bookmark },
  { title: "Notifications", url: "/notifications", icon: Bell },
  { title: "Integrations", url: "/settings/integrations", icon: Puzzle },
  {
    title: "Settings",
    icon: Settings,
    sub: [
      { title: "Business Settings", url: "/settings/business" },
      { title: "Business Location", url: "/settings/locations" },
      { title: "Warehouses", url: "/settings/warehouses" },
      { title: "Team", url: "/settings/users" },
      { title: "Roles & Permissions", url: "/settings/roles" },
      { title: "Currency", url: "/settings/currency" },
      { title: "Tax Settings", url: "/settings/taxes" },
      { title: "Receiving Accounts", url: "/settings/payments/business-accounts" },
      { title: "Payout Accounts",    url: "/settings/payments/accounts" },
      { title: "Payment Settings", url: "/settings/payments" },
      { title: "Invoice Settings", url: "/settings/invoice" },
      { title: "Receipt Printers", url: "/settings/printers" },
      { title: "Barcode Settings", url: "/settings/barcodes" },
      { title: "Notification Settings", url: "/settings/notifications" },
      { title: "Security", url: "/settings/security" },
      { title: "Preferences", url: "/settings/preferences" },
      { title: "Profile", url: "/settings/profile" },
    ],
  },
  { title: "Help", url: "/help/glossary", icon: FileText },
]

// Primary destinations exposed in the mobile bottom nav. Picked for
// "most-used" rather than full coverage — everything else falls into
// the More drawer.
export const BOTTOM_NAV_PRIMARY: { title: string; url: string; icon: LucideIcon }[] = [
  { title: "Home", url: "/dashboard", icon: BarChart3 },
  { title: "POS", url: "/pos", icon: CreditCard },
  { title: "Stock", url: "/inventory", icon: Package2 },
  { title: "Sales", url: "/sales/orders", icon: ShoppingCart },
]
